name: test-and-coverage

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-tests-get-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0 # it is HIGHLY recommended to pin this to a release
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry virtualenv
        run: poetry install

      - name: Run tests
        run: poetry run tox
