name: test-and-coverage

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0 # it is HIGHLY recommended to pin this to a release
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry virtualenv
        run: poetry install

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: poetry run tox

      - name: Send partial results to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: poetry run coveralls --service=github

  test-optional:  # This is allowed to fail and the coveralls job will still run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11.0-beta.5']
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0 # it is HIGHLY recommended to pin this to a release
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry virtualenv
        run: poetry install

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: poetry run tox

      - name: Send partial results to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: poetry run coveralls --service=github

  coveralls:
    name: Indicate completion to coveralls.io
    needs: [test, test-optional]
    if: ${{ success() || needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0 # it is HIGHLY recommended to pin this to a release
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry virtualenv
        run: poetry install

      - name: Signal Finished
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install --upgrade coveralls
          poetry run coveralls --service=github --finish
